version: "3.8"

services:
  example-backend:
    image: backend-project
    container_name: mooc-backend
    ports:
      - "8080:8080"
  example-frontend:
    image: frontend-project
    container_name: mooc-frontend
    ports:
      - "5000:5000"

  