version: "3.8"

services:
  example-backend:
    image: backend-project
    container_name: mooc-backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=salainen
    ports:
      - "8080:8080"
  example-frontend:
    image: frontend-project
    container_name: mooc-frontend
    ports:
      - "5000:5000"
  redis-storage:
    image: redis:6-alpine
    container_name: redis
  database:
    image: postgres:13.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: salainen
