version: "3.8"

services:
  backend:
    image: backend
    build: ./ml-kurkkumopo-backend
    ports:
      - "5000:5000"
    volumes:
      - model:/src/model
    depends_on:
      - model
  frontend:
    image: frontend
    build: ./ml-kurkkumopo-frontend
    ports:
      - "3000:3000"
  training:
    image: training
    build: ./ml-kurkkumopo-training
    volumes:
      - imgs:/src/imgs
      - data:/src/data
      - model:/src/model
volumes:
  imgs:
  data:
  model: